include(${CMAKE_CURRENT_LIST_DIR}/Common/LogHelper.cmake)

find_path(log4cplus_INCLUDE_DIR NAMES log4cplus/logger.h log4cplus/configurator.h log4cplus/loggingmacros.h PATHS ${log4cplus_INCLUDEDIR})

if(WIN32)
    list(LENGTH CMAKE_CONFIGURATION_TYPES ConfigCount)
    if(ConfigCount EQUAL 1)
        list(GET CMAKE_CONFIGURATION_TYPES 0 ConfigType)
        if(ConfigType STREQUAL "Debug")
            SET(log4cplus_LIBRARY_NAME_DEBUG "log4cplusD")
        else()
            SET(log4cplus_LIBRARY_NAME_RELEASE "log4cplus")
        endif()
    else()
        set(log4cplus_LIBRARY_NAME_DEBUG "log4cplusD")
        set(log4cplus_LIBRARY_NAME_RELEASE "log4cplus")
    endif()
else()
    set(log4cplus_LIBRARY_NAME_DEBUG "log4cplus")
    set(log4cplus_LIBRARY_NAME_RELEASE "log4cplus")
endif()

if(log4cplus_LIBRARY_NAME_DEBUG)
    get_filename_component(log4cplus_LIBRARY_DIR_DEBUG ./Debug ABSOLUTE BASE_DIR ${log4cplus_LIBRARYDIR})
    LogDebug("Debug library to be find:${log4cplus_LIBRARY_DIR_DEBUG}/${log4cplus_LIBRARY_NAME_DEBUG}")
    find_library(log4cplus_LIBRARY_DEBUG "${log4cplus_LIBRARY_NAME_DEBUG}" PATHS ${log4cplus_LIBRARY_DIR_DEBUG})
    if(log4cplus_LIBRARY_DEBUG)
        set(log4cplus_LIBRARY_DEBUG ${log4cplus_LIBRARY_DEBUG} CACHE PATH "log4cplus debug library path" FORCE)
    endif()
    if(WIN32)
        LogDebug("Win32 debug dll library to be find:${log4cplus_LIBRARY_DIR_DEBUG}/${log4cplus_LIBRARY_NAME_DEBUG}.dll")
        find_file(log4cplus_DLL_LIBRARY_DEBUG "${log4cplus_LIBRARY_NAME_DEBUG}.dll" PATHS ${log4cplus_LIBRARY_DIR_DEBUG})
        if(log4cplus_DLL_LIBRARY_DEBUG)
            set(log4cplus_DLL_LIBRARY_DEBUG ${log4cplus_DLL_LIBRARY_DEBUG} CACHE PATH "log4cplus debug windows dll library path" FORCE)
        endif()
    endif()
endif()
if(log4cplus_LIBRARY_NAME_RELEASE)
    get_filename_component(log4cplus_LIBRARY_DIR_RELEASE ./Release ABSOLUTE BASE_DIR ${log4cplus_LIBRARYDIR})
    LogDebug("Release library to be find:${log4cplus_LIBRARY_DIR_RELEASE}/${log4cplus_LIBRARY_NAME_RELEASE}")
    find_library(log4cplus_LIBRARY_RELEASE "${log4cplus_LIBRARY_NAME_RELEASE}" PATHS ${log4cplus_LIBRARY_DIR_RELEASE})
    if(log4cplus_LIBRARY_RELEASE)
        set(log4cplus_LIBRARY_RELEASE ${log4cplus_LIBRARY_RELEASE} CACHE PATH "log4cplus release library path" FORCE)
    endif()
    if(WIN32)
        LogDebug("Win32 debug dll library to be find:${log4cplus_LIBRARY_DIR_RELEASE}/${log4cplus_LIBRARY_NAME_RELEASE}.dll")
        find_file(log4cplus_DLL_LIBRARY_RELEASE "${log4cplus_LIBRARY_NAME_RELEASE}.dll" PATHS ${log4cplus_LIBRARY_DIR_RELEASE})
        if(log4cplus_DLL_LIBRARY_RELEASE)
            set(log4cplus_DLL_LIBRARY_RELEASE ${log4cplus_DLL_LIBRARY_RELEASE} CACHE PATH "log4cplus release windows dll library path" FORCE)
        endif()
    endif()
endif()

if(NOT log4cplus_INCLUDE_DIR OR ((WIN32 AND (NOT log4cplus_LIBRARY_DEBUG OR NOT log4cplus_DLL_LIBRARY_DEBUG)) AND (WIN32 AND (NOT log4cplus_LIBRARY_RELEASE OR NOT log4cplus_DLL_LIBRARY_RELEASE))) OR (NOT log4cplus_LIBRARY_DEBUG AND NOT log4cplus_LIBRARY_RELEASE))
    message(FATAL_ERROR "Unable to find the requested log4cplus library,please set log4cplus_INCLUDEDIR and log4cplus_LIBRARYDIR to right path.")
else()
    set(log4cplus_FOUND TRUE)
    message(STATUS "Found log4cplus library")
    message(STATUS "  Include path: " ${log4cplus_INCLUDE_DIR})
    add_library(log4cplus SHARED IMPORTED)
    set_target_properties(log4cplus PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${log4cplus_INCLUDE_DIR})
    if(log4cplus_LIBRARY_DEBUG)
        if(WIN32)
            set_target_properties(log4cplus PROPERTIES IMPORTED_LOCATION_DEBUG ${log4cplus_DLL_LIBRARY_DEBUG})
            set_target_properties(log4cplus PROPERTIES IMPORTED_IMPLIB_DEBUG ${log4cplus_LIBRARY_DEBUG})
            message(STATUS "  Debug library path: " ${log4cplus_DLL_LIBRARY_DEBUG})
            message(STATUS "  Debug imported library path: " ${log4cplus_LIBRARY_DEBUG})
        else()
            set_target_properties(log4cplus PROPERTIES IMPORTED_LOCATION_DEBUG ${log4cplus_LIBRARY_DEBUG})
            message(STATUS "  Debug library path: " ${log4cplus_LIBRARY_DEBUG})
        endif()
    endif()
    if(log4cplus_LIBRARY_RELEASE)
        if(WIN32)
            set_target_properties(log4cplus PROPERTIES IMPORTED_LOCATION_RELEASE ${log4cplus_DLL_LIBRARY_RELEASE})
            set_target_properties(log4cplus PROPERTIES IMPORTED_IMPLIB_RELEASE ${log4cplus_LIBRARY_RELEASE})
            set_target_properties(log4cplus PROPERTIES IMPORTED_LOCATION_RELWITHDEBINFO ${log4cplus_DLL_LIBRARY_RELEASE})
            set_target_properties(log4cplus PROPERTIES IMPORTED_IMPLIB_RELWITHDEBINFO ${log4cplus_LIBRARY_RELEASE})
            message(STATUS "  Release library path: " ${log4cplus_DLL_LIBRARY_RELEASE})
            message(STATUS "  Release imported library path: " ${log4cplus_LIBRARY_RELEASE})
        else()
            set_target_properties(log4cplus PROPERTIES IMPORTED_LOCATION_RELEASE ${log4cplus_LIBRARY_RELEASE})
            set_target_properties(log4cplus PROPERTIES IMPORTED_LOCATION_RELWITHDEBINFO ${log4cplus_LIBRARY_RELEASE})
            message(STATUS "  Release library path: " ${log4cplus_LIBRARY_RELEASE})
        endif()
    endif()
endif()